apiVersion: v1
kind: Pod
metadata:
  name: aspnetapp2
  labels:
    app: aspnetapp2
spec:
  containers:
  - image: "mcr.microsoft.com/dotnet/core/samples:aspnetapp"
    name: aspnetapp-image
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aspnetapp2
spec:
  selector:
    app: aspnetapp2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: aspnetapp2
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: true
    cert-manager.io/cluster-issuer: letsencrypt
    cert-manager.io/acme-challenge-type: http01
spec:
  tls:
  - hosts:
    - test-app2.k8s.az.justinseely.ca
    secretName: test-app2-tls
  rules:
  - host: test-app2.k8s.az.justinseely.ca
    http:
      paths:
      - path: /
        backend:
          serviceName: aspnetapp2
          servicePort: 80
